# Generated by Django 3.2.13 on 2022-05-31 14:17

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites', jsonfield.fields.JSONField(default=dict)),
                ('user', models.TextField()),
            ],
        ),
    ]
